services:
  mysql_db:
    image: mysql:latest
    container_name: mysql_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    ports:
      - "10001:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uuser", "-p123456"]
      interval: 10s
      retries: 5
      start_period: 30s

  mongo_db:
    image: mongo:latest
    container_name: mongo_container
    restart: unless-stopped
    ports:
      - "10002:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: products_db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 10s
      retries: 5
      start_period: 30s

  postgres_db:
    image: postgres:latest
    container_name: postgres_container
    restart: unless-stopped
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
    ports:
      - "10003:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d orders_db"]
      interval: 10s
      retries: 5
      start_period: 30s

  user_service:
    build: ./user-service
    container_name: user_service_container
    restart: unless-stopped
    ports:
      - "10004:8000"
    depends_on:
      mysql_db:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql+aiomysql://user:123456@mysql_db:3306/user_db
    volumes:
      - ./user-service:/app

  product_service:
    build: ./product-service
    container_name: product_service_container
    restart: unless-stopped
    ports:
      - "10005:8000"
    depends_on:
      mongo_db:
        condition: service_healthy
    environment:
      DATABASE_URL: mongodb://mongo_db:27017
      DATABASE_NAME: products_db
    volumes:
      - ./product-service:/app

  gateway:
    build: ./gateway
    container_name: gateway_container
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: secret_key
      HASH_ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRES: 1440
      REFRESH_TOKEN_EXPIRES: 10080
      USER_SERVICE_URL: http://user_service:8000
      PRODUCT_SERVICE_URL: http://product_service:8000
    volumes:
      - ./gateway:/app

volumes:
  mysql_data:
  mongo_data:
  postgres_data: