import os


SECRET_KEY: str = os.getenv("SECRET_KEY")
HASH_ALGORITHM: str = os.getenv("HASH_ALGORITHM")
ACCESS_TOKEN_EXPIRES: int = int(os.getenv("ACCESS_TOKEN_EXPIRES"))
REFRESH_TOKEN_EXPIRES: int = int(os.getenv("REFRESH_TOKEN_EXPIRES"))
USER_SERVICE_URL: str = os.getenv("USER_SERVICE_URL")
PRODUCT_SERVICE_URL: str = os.getenv("PRODUCT_SERVICE_URL")